#!/usr/bin/env python

from subprocess import Popen, PIPE
import re
import os
import requests
import datetime

# Set time of script
now = datetime.datetime.now()

# Clean up and recreate temp file generated by the script
filepath = '/tmp/output.txt'
try:
	os.remove(filepath)
except:
	print 'No file to remove!'
text_file = open(filepath, "a")

# Create log file, open, and add start time and date
logfilepath = '/var/log/net_scan.log'
log_file = open(logfilepath, "a")
log_file.write("%s: Starting a new scan.\n" % now.strftime("%Y-%m-%d %H:%M:%S"))

# Create a list in memory of known hosts to compare to this run
known_lines = []
with open("/opt/scripts/netscan/known_hosts") as file:
        for line in file:
                line = line.strip()
                known_lines.append(line)

for i in range(1,255, 1): 
        try:
            IP = '192.168.1.%s' % i 
            pid = Popen(["arp", "-n", IP], stdout=PIPE)
            s = pid.communicate()[0]
            mac = re.search(r"(([a-f\d]{1,2}\:){5}[a-f\d]{1,2})", s).groups()[0]
            if mac.upper() in known_lines:
                log_file.write("Match for %s with IP %s\n" % (mac.upper(), IP))
            else:
                print 'No match for %s' % mac
                resp = requests.post('https://textbelt.com/text', {
                    'phone': '1234567890',
                    'message': 'Unknown MAC address found on network.',
                    'key': 'no key for you',
                    })
                print(resp.json())
        except:
            # Have to have an exception for non active IP addresses
            text_file.write("%s is not active.\n" % IP)
            pass
	
# Close text file
text_file.close
log_file.close
